kind: pipeline
name: Pipeline

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build

- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: zelfick/go-droneci
    tags:
      - 0.0.1
      - latest
  when:
    branch:
    - master

- name: notify
  image: drillster/drone-email
  settings: 
    host: smtp
    username: user
    password: pwd
    port: 25
    skip_verify: true
    from: pipeline@cloud.drone.io
    recipients: [jorgeherran@hotmail.com, jorgeandresherran@gmail.com]
    when:
      status: [ changed, failure ]

services:

- name: smtp
  image: catatnight/postfix
  environment:
    ports: 25
    maildomain: cloud.drone.io
    smtp_user: user:pwd
    messageSizeLimit: 40960000
    mailboxSizeLimit: 40960000

