kind: pipeline
name: Pipeline

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build

- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

#services:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: zelfick/go-droneci
    tags:
      - 1.0.2
      - latest
  when:
    branch:
    - master